# Generated by Django 5.1.4 on 2025-02-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usuario_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='reset_token_expira',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='reset_token',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True),
        ),
    ]
