site_name: "2024.2-Gemini"
site_url: "https://fga0138-mds-ajax.github.io/2024.2-Gemini/"
repo_url: "https://github.com/fga0138-mds-ajax/2024.2-Gemini"
repo_name: "fga0138-mds-ajax/2024.2-Gemini"

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: 'green'
      accent: 'light green'
      toggle:
        icon: material/brightness-7
        name: Mudar para o modo escuro

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: "deep purble"
      accent: "#abcbe6"
      toggle:
        icon: material/brightness-4
        name: Mudar para a preferência do sistema

  language: pt-BR
  #favicon: assets/arquivo.png
  #logo: assets/arquivo.png

  icon:
    repo: fontawesome/solid/code-branch
    logo: material/book
    search: material/magnify


nav:
  - Início: "index.md"
  - Documento de Visão: "documento-visao/documento-visao.md"
  - Documento de Requisitos: "documento-requisitos/documento-requisitos.md"
  - Documento de Arquitetura: "documento-arquitetura/documento-arquitetura.md"
  - Documento de Plano de Testes: "documento-plano-testes/documento-plano-testes.md"
  - Atas de Reunião:
    - Ata 1: "atas-reuniao/ata-reuniao-1.md"
    - Ata 2: "atas-reuniao/ata-reuniao-2.md"
    - Ata 3: "atas-reuniao/ata-reuniao-3.md"
    - Ata 4: "atas-reuniao/ata-reuniao-4.md"
    - Ata 5: "atas-reuniao/ata-reuniao-5.md"
    - Ata 6: "atas-reuniao/ata-reuniao-6.md"
    - Ata 7: "atas-reuniao/ata-reuniao-7.md"
    - Ata 8: "atas-reuniao/ata-reuniao-8.md"
    - Ata 9: "atas-reuniao/ata-reuniao-9.md"
    - Ata 10: "atas-reuniao/ata-reuniao-10.md"
    - Ata 11: "atas-reuniao/ata-reuniao-11.md"
    - Ata 12: "atas-reuniao/ata-reuniao-12.md"
    - Ata 13: "atas-reuniao/ata-reuniao-13.md"
    - Ata 14: "atas-reuniao/ata-reuniao-14.md"
    - Ata 15: "atas-reuniao/ata-reuniao-15.md"
    - Ata 16: "atas-reuniao/ata-reuniao-16.md"
    - Ata 17: "atas-reuniao/ata-reuniao-17.md"
    - Ata 18: "atas-reuniao/ata-reuniao-18.md"
    - Ata 19: "atas-reuniao/ata-reuniao-19.md"
    - Ata 20: "atas-reuniao/ata-reuniao-20.md"
    
extra:
  version:
    provider: mike