export {default as Cadastro} from './Cadastro/Cadastro';
export {default as Camiseta1} from './Camisetas/Camiseta1';
export {default as Camiseta2} from './Camisetas/Camiseta2';
export {default as Carrinho} from './Carrinho/Carrinho.jsx';
export {default as Checkout} from './Checkout/Checkout.jsx';
export {default as Historia} from './Historia/Historia.jsx';
export {default as Login} from './Login/Login.jsx';
export {default as Patrocinadores} from './Patrocinadores/Patrocinadores.jsx';
export {default as PosVenda} from './PosVenda/PosVenda.jsx'
export {default as Produtos} from './Produtos/Produtos.jsx';
export {default as Usuario} from './Usuario/Usuario.jsx' 
export {default as RecuperarSenha} from './RecuperarSenha/RecuperarSenha.jsx';