export {default as CamisetaNoCarrinho} from './CamisetaNoCarrinho/CamisetaNoCarrinho.jsx';
export {default as CamisetaNoCheckOut} from './CamisetaNoCheckOut/CamisetaNoCheckOut.jsx';
export {default as CamposDeCadastro} from './CamposDeCadastro/CamposDeCadastro.jsx';
export {default as CamposDeIndentificacao} from './CamposDeIdentificacao/CamposDeIdentificacao.jsx';
export {default as CamposDeLogin} from './CamposDeLogin/CamposDeLogin.jsx';
export {default as CardCamiseta} from './CardCamiseta/CardCamiseta.jsx';
export {default as Carrossel} from './Carrossel/Carrossel.jsx';
export {default as Footer} from './Footer/Footer.jsx';
export {default as FooterResumido} from './FooterResumido/FooterResumido.jsx';
export {default as Header} from './Header/Header.jsx';
export {default as MenuCamiseta} from './MenuCamiseta/MenuCamiseta.jsx';
export {default as MenuUsuario} from './MenuUsuario/MenuUsuario.jsx';
export {default as ResumoPagamento} from './ResumoPagamento/ResumoPagamento.jsx'
