# Generated by Django 5.1.4 on 2025-02-06 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id_banner', models.AutoField(primary_key=True, serialize=False)),
                ('nome_banner', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='banners/')),
            ],
        ),
    ]
