# Generated by Django 5.1.4 on 2025-01-24 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_categoria_atualidzado_em'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='atualidzado_em',
            new_name='atualizado_em',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='atualidzado_em',
            new_name='atualizado_em',
        ),
    ]
